version: 2
jobs:
  build:
     machine: true
     steps:
       - checkout
       - run: python -m pip install datetime
       - run: python /home/circleci/project/Chatapp/Chatapp/Test/test_accessFiles.py