version: 2
jobs:
  build:
     machine: true
     steps:
       - checkout
       - run: python -m pip install datetime
       - run: python -m unittest ~/project/Chatapp/Chatapp/Test/accessFiles_test.py